### ISSUE TITLE
Updated damage values not showing

### ISSUE THREAD

**Issue by DamageMaximo** [calware/BetterChef#1]
![image](https://github.com/user-attachments/assets/516267dd-1bf3-447f-b7d4-c0becae944f4)
**Shouldn't it say 600%-1200%?**
![image](https://github.com/user-attachments/assets/4414202e-d30a-4463-8592-beae0cca32ed)
**Also shouldn't this say it deals more damage the closer you are to the target?**

also quick little question, is a mod like this for seeker and false son planned? because I'd like to use this mod without any bugs happening because the mods aren't compatible with each other because of the CHEF changes

**Comment by calware** [comment]
Hey thank you for your message! I'll investigate the issues you raised tonight along with the first major patch we push out. Compatibility with base StormTweaks can vary depending on a lot of different factors, including mod load ordering, which changes are toggled in which configs, and so on. One way you may be able to force compatibility is by only having one of the mods make changes to specific skills (rather than enabling both in both mods); such as disabling Dice changes + Roll oil in StormTweaks, but enabling it in BetterChef. In replicating some of these changes, however, I am curious: what bugs specifically are you experiencing with including both BetterChef and StormTweaks? Thanks again for your message :)

**Comment by DamageMaximo** [comment]
Hey, I hadn't tested it with both enabled at the time I posted that, bugs can be so unpredictable I was worried having both enabled could do something bad like somehow corrupting my save file (remember what was happening to the playstation players?), I've just tried that and so far the only bug I found was the "YES CHEF" buffed Sear lasts for longer than the animation shows, I didn't find anything else, not noticed any perfomance issues either, the same happens with the CHEF changes disabled in Storm Tweaks. I didn't think about disabling the changes in one mod so thanks for that!

**Comment by calware** [comment]
@DamageMaximo Would you mind sharing some details as to what other mods you may have had loaded at the time where you were unable to see these menu changes? I am unable to replicate this behavior on my machine or on the machines of some others I've asked to try out the mod. Did you get any error messages in your BepInEx console that had to do with BetterChef failing in an `Init` function? Thank you for the added notes about the Sear animation!

**Comment by DamageMaximo** [comment]
I've just finished restarting the game like 20 times each time with different mods and I found out the one causing the skill description problem is the UnifiedItemDescriptions mod

**Comment by calware** [comment]
Alright :) @DamageMaximo thank you for doing all that testing and figuring things to that end. When the UnifiedItemDescriptions mod doesn't interfere, are you able to see the descriptions for the skills change? Additionally, what was the note you had about making BetterChef compatible with other SOTS mods? Was that purely related to StormTweaks or to some other mods?

**Comment by DamageMaximo** [comment]
Yes, without UnifiedItemDescriptions I can see the updated description, StormTweaks was the only mod I had in mind which also messes with CHEF's workings but is also undisposable because it does other good things as well.

**Comment by calware** [comment]
I'm going to close this issue up then and merge your point about SOTS compatibility with something we have in the works. Do let me know if you'd like anything re-approached, or if you come into that issue again in the future :) Thank you for the heads up regardless!
